using BaseLib.Abstracts;
using Invoker.Scripts.Keywords;
using Invoker.Scripts.Relics;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Models;

namespace Invoker.Scripts.Cards;

/// <summary>
/// Base class for all Invoker spell cards (generated by InvokeCard).
/// 1-cost cards added to hand; provides enhancement check.
/// Concrete subclasses must apply [Pool(typeof(InvokerCardPool))].
/// </summary>
public abstract class SpellCardBase : CustomCardModel
{
    public override IEnumerable<CardKeyword> CanonicalKeywords => [InvokerKeywords.Scroll, CardKeyword.Exhaust];

    protected SpellCardBase(CardType type, TargetType targetType, CardRarity rarity = CardRarity.Uncommon, int cost = 1)
        : base(cost, type, rarity, targetType)
    {
    }

    /// <summary>
    /// Returns true if the player's equipped command stone enhances this spell.
    /// Subclasses provide the (q, w, e) combination to check.
    /// </summary>
    protected bool IsEnhanced()
    {
        var stone = Owner.Relics.OfType<QuasCommandStone>().FirstOrDefault() as object
                    ?? Owner.Relics.OfType<WexCommandStone>().FirstOrDefault() as object
                    ?? Owner.Relics.OfType<ExortCommandStone>().FirstOrDefault() as object;

        return stone switch
        {
            QuasCommandStone q => QuasCommandStone.Enhances(SpellQ, SpellW, SpellE),
            WexCommandStone w  => WexCommandStone.Enhances(SpellQ, SpellW, SpellE),
            ExortCommandStone e => ExortCommandStone.Enhances(SpellQ, SpellW, SpellE),
            _ => false,
        };
    }

    // Each spell declares its own orb combination for enhancement checks
    protected abstract int SpellQ { get; }
    protected abstract int SpellW { get; }
    protected abstract int SpellE { get; }
}
