using BaseLib.Patches.Content;
using MegaCrit.Sts2.Core.Entities.Cards;

namespace Invoker.Scripts.Keywords;

/// <summary>
/// Custom CardKeyword enum values for Invoker mod.
/// Registered via BaseLib's [CustomEnum] attribute during ModelDb.Init().
/// </summary>
public static class InvokerKeywords
{
    /// <summary>
    /// Scroll keyword — used by all spell cards generated by Invoke.
    /// ID: "INVOKER-SCROLL" (namespace prefix "INVOKER-" + field name "SCROLL")
    /// </summary>
    [CustomEnum]
    public static CardKeyword Scroll;

    /// <summary>
    /// Invoke keyword — used by cards that trigger the Invoke effect.
    /// ID: "INVOKER-INVOKE" (namespace prefix "INVOKER-" + field name "INVOKE")
    /// </summary>
    [CustomEnum]
    public static CardKeyword Invoke;
}
